# Dimentional Array

In [78]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


## 2 dimentional array

In [79]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [80]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.sum([a,b],axis = 1)
c

array([ 6, 15])

In [81]:
a = np.array([1,2,3])
b = np.array([8,9,0])
c = np.sum([a,b],axis = 0)
print(c)

[ 9 11  3]


In [82]:
print(np.exp(a))
print(np.sqrt(b))
print(np.sin(b))
print(np.cos(b))

[ 2.71828183  7.3890561  20.08553692]
[2.82842712 3.         0.        ]
[0.98935825 0.41211849 0.        ]
[-0.14550003 -0.91113026  1.        ]


In [83]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.equal(a,b)

array([False, False,  True])

In [84]:
a = [1,2,3]
b = [5,6,7]
c = [1,2,3]

np.array_equal(a,c)

True

Initialize all the elements of x X y array to 0

In [85]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
import numpy as np
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
import numpy as np
np.full((3,4),1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [88]:
import numpy as np
arr = np.zeros((4,3))

In [89]:
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:
import numpy as np
np.arange(1,10,4)

array([1, 5, 9])

In [91]:
import numpy as np
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [92]:
import numpy as np
arr = np.full((4,5),2.09)
print(arr)

[[2.09 2.09 2.09 2.09 2.09]
 [2.09 2.09 2.09 2.09 2.09]
 [2.09 2.09 2.09 2.09 2.09]
 [2.09 2.09 2.09 2.09 2.09]]


In [93]:
import numpy as np
zeros = np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
arr = np.full((4,3),8)
arr

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [95]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [96]:
arr = np.arange(0,10,3)

In [97]:
s = np.array([[1,2,3,4],[2,3,4,5],[6,7,8,9]])
print(s.shape)

(3, 4)


In [98]:
a = np.array([[1,2],[2,3],[4,5]])
print(a.shape)

(3, 2)


In [99]:
i = np.array([[9,0],[0,0],[9,0,8]])
print(i.shape)

(3,)


<ipython-input-99-0b190d5d4309>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  i = np.array([[9,0],[0,0],[9,0,8]])


## Inspecting the array: resize the array

In [100]:
a = np.array([[2,3,4],[4,5,6]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 4]
 [5 6]]


In [101]:
a.size

6

In [102]:
a = np.array([[1,2,3]])

In [103]:
print(a)
print(b)

[[1 2 3]]
[5, 6, 7]


## Find the datatype of the array

In [105]:
a = np.arange(24, dtype=float)
print(a)
print(a.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
float64


## Numpy array mathematics

## summation

In [106]:
import numpy as np
np.sum([10,20])

30

In [107]:
a,b = 10,20
np.sum([a,b])

30

In [108]:
np.sum([[1,2],[5,6]], axis = 0)

array([6, 8])

In [109]:
np.sum([[1,2],[5,6]], axis = 1)

array([ 3, 11])

In [110]:
np.sum([[1,2],[5,6]])

14

## Numpy array subtraction

In [112]:
np.subtract(10,20)

-10

## all other mathematical function

In [113]:
np.multiply(2,3)  #multiply two numbers

6

In [115]:
np.divide(10,2)

5.0

In [116]:
a = np.array([2,4,6])
b = np.array([1,2,3])
np.multiply(a,b)

array([ 2,  8, 18])

In [117]:
#exp,sqrt,sin,cos,log
print("Exponent : ", np.exp(a))
print("Square root : ", np.sqrt(a))
print("sin : ", np.sin(a))
print("cos : ", np.cos(a))

Exponent :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
cos :  [-0.41614684 -0.65364362  0.96017029]


## Array comparision

In [119]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.array_equal(a,c)
np.equal(a,b)

array([False, False,  True])

## Aggregate function

In [120]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
print("sum", np.sum(a))
print("Minimum value: ", np.min(a))
print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Standard Deviation: ", np.std(a))


sum 7
Minimum value:  1
Mean:  2.3333333333333335
Median:  2.0
Standard Deviation:  1.247219128924647


## Concept of Broadcasting

In [121]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First array: \n",a,"\n")
print("second array: \n",b,"\n")
print("Third array :\n",c,"\n")
print("First Array + Second Array: \n",a+b,"\n")

First array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

second array: 
 [[0 1 2]] 

Third array :
 [1, 2, 4] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



## Indexing and slicing in python

In [122]:
a = ['m','o','n','t','h','l','y',' ','p','y','t','h','o','n']
a[2:9]

['n', 't', 'h', 'l', 'y', ' ', 'p']

In [127]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]
a[:1]
print(a)
a[:1,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3]])

In [129]:
a.size

9

In [130]:
a[:1][0][1:]

array([2, 3])

## Array manipulation in python

In [132]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [133]:
#stact array row:wise: horizontal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [135]:
#stack array row-wise: vertically
print(a)
print(b)
np.vstack((a,b))

[1 2 3]
[4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
i = np.arange(0,100,5)
print(i)
print(i.size)
i.shape = 5,2,2
print(i)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
20
[[[ 0  5]
  [10 15]]

 [[20 25]
  [30 35]]

 [[40 45]
  [50 55]]

 [[60 65]
  [70 75]]

 [[80 85]
  [90 95]]]


In [160]:
i.shape = (2,5,2)
print(i)
np.hsplit(i,5)

[[[ 0  5]
  [10 15]
  [20 25]
  [30 35]
  [40 45]]

 [[50 55]
  [60 65]
  [70 75]
  [80 85]
  [90 95]]]


[array([[[ 0,  5]],
 
        [[50, 55]]]),
 array([[[10, 15]],
 
        [[60, 65]]]),
 array([[[20, 25]],
 
        [[70, 75]]]),
 array([[[30, 35]],
 
        [[80, 85]]]),
 array([[[40, 45]],
 
        [[90, 95]]])]